# Generated by Django 4.2.3 on 2023-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_imc'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
