# Generated by Django 4.2.3 on 2023-07-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_estado_mc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='imc',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
